### ISSUE TITLE
Foiled by Uber: npm install fails when it tries to pull in an internal Uber dependancy.

### ISSUE THREAD

**Issue by DDR0** [jamesmanning/emotebuilder#5]
Trying to build the emotebuilder, I encountered the problem after `git fetch` and `npm install`. (I was trying to add an event listener on menu select change, so I could see the emote graphic without having to hit 'enter' each time.)

The relevant package is `asap@https://unpm.uberinternal.com/asap/-/asap-2.0.4.tgz`, which seems to be a sub-package of something.

```
…
22643 silly extract invert-kv@1.0.0
22644 verbose unlock done using /home/david/.npm/_locks/staging-cd906f0b27572ec5.lock for /home/david/html/emotebuilder/node_modules/.staging
22645 warn @angular/core@2.4.10 requires a peer of zone.js@^0.7.2 but none was installed.
22646 warn ng2-bootstrap@1.6.3 requires a peer of @angular/common@^2.3.1 || >=4.0.0 but none was installed.
22647 warn ng2-bootstrap@1.6.3 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0 but none was installed.
22648 warn ng2-bootstrap@1.6.3 requires a peer of @angular/core@^2.3.1 || >=4.0.0 but none was installed.
22649 warn ng2-bootstrap@1.6.3 requires a peer of @angular/forms@^2.3.1 || >=4.0.0 but none was installed.
22650 warn optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.0 (node_modules/angular-cli/node_modules/npm/node_modules/has-unicode):
22651 warn package.json SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/home/david/html/has-unicode/package.json'
22652 verbose package.json SKIPPING OPTIONAL DEPENDENCY: npm can't find a package.json file in your current directory.
22653 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
22654 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/david/html/emotebuilder/node_modules/.staging/fsevents-14fe528b/node_modules/strip-ansi' -> '/home/david/html/emotebuilder/node_modules/.staging/strip-ansi-e748e65e'
22655 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
22655 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
22656 verbose type OperationalError
22657 verbose stack Error: 401 Unauthorized: asap@https://unpm.uberinternal.com/asap/-/asap-2.0.4.tgz
22657 verbose stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
22657 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
22657 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
22657 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
22657 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
22657 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
22657 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
22657 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
22657 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
22657 verbose stack     at runCallback (timers.js:800:20)
22657 verbose stack     at tryOnImmediate (timers.js:762:5)
22657 verbose stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
22658 verbose cwd /home/david/html/emotebuilder
22659 verbose Linux 4.8.0-58-generic
22660 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
22661 verbose node v8.1.4
22662 verbose npm  v5.3.0
22663 error code E401
22664 error 401 Unauthorized: asap@https://unpm.uberinternal.com/asap/-/asap-2.0.4.tgz
22665 verbose exit [ 1, true ]
```

Thanks for making the page! It's great. :)

**Comment by jamesmanning** [comment]
This is a new one for me.  A search ran across this issue from the asap package's repo.  Could you try the clean/rm/install steps listed here to see if it helps? https://github.com/kriskowal/asap/issues/70

**Comment by DDR0** [comment]
I've given the steps listed there a shot, but still had no luck. I can install asap just fine myself, using `npm install asap`, which gives v2.0.6 instead of 2.0.4 though. That doesn't help me install, though.

I've uploaded a slightly doctored log detailing the results at https://gist.github.com/DDR0/ea763213ca0f631b2bd7b7baf74a535d. (I had really fat-fingered it.)

**Comment by nonnenmacher** [comment]
Got this too after someone, cleared a server node_modules by `rm -rf`.
Weird !

**Comment by jamesmanning** [comment]
@nonnenmacher whoa, that's great to know!  I don't see anything in the current package.json that would cause that.

I had tried to upgrade angular to a newer version but it ended up being a lot more effort than I had expected.  I'll try again today, though, since I need to either keep this updated with current angular versions or go ahead with the potential vue or react rewrite I keep thinking about doing. 😄

**Comment by jamesmanning** [comment]
no longer using angular so this issue shouldn't happen any longer
